---
title: "Introduction to Linear Algebra -- 第六章(2)：微分方程，傅里叶级数"
author: "bourneli"
date: "2016年7月"
output: html_document
---

本章介绍矩阵作用到连续数据上的应用 

* 常系数微分方程
* 傅里叶级数

## 微分方程

回顾常系数纤细微分方程，

$$
  \frac{dy}{dt} = ay
$$


其解为，

$$
  y = Ce^{at}
$$

直接代入可以验证。

### 常系数微分方程扩展到矩阵形式

$$
  \frac{du}{dt}=Au
$$


### 例1:$2 \times 2$矩阵

$$
  \frac{du_1}{dt}=-u_1+2u_2,
  \frac{du_2}{dt}=u_1-2u_2,
  u(0)=\begin{bmatrix}1 \\ 0\end{bmatrix}
$$

将上面的方程组用向量与矩阵表示，如下

$$
  \frac{du}{dt}=\begin{bmatrix}-1 & 2 \\ 1 &-2\end{bmatrix}
  \begin{bmatrix}u_1 \\ u_2\end{bmatrix} = Au
$$

A是奇异矩阵，那么必有$\lambda_1 = 0$，再由特征值之和等于矩阵迹，容易得到$\lambda_2=-3$，后面再用通用计算方法验证一下。

根据特征值，计算出特征向量如下，

$$
  x_1=\begin{bmatrix}2 \\ 1\end{bmatrix},
  x_2=\begin{bmatrix}1 \\ -1\end{bmatrix}
$$

$2\times 2$矩阵解的通用形式如下

$$
  u(t)=C_1e^{\lambda_1t}x_1 + C_2e^{\lambda_2t}x_2 
  \approx C_1{\lambda_1^t}x_1 + C_2{\lambda_2^t}x_2,
  (u_{k+1}=Au_k)
$$

与上次课程产生联系(一个是离散，一个是连续)，当$t \rightarrow \infty$成立。

$$
  u = Ce{\lambda t}x \qquad (1)
$$

纯解，可以将(1)代入到微分方程，很容易得到两边相等，剩下的问题就是确定常数$C$。上面的公式恒等，那么在$t=0$的情况下也成立，直接代入，等价解一个二元线性方程组，如下

$$
  C_1\begin{bmatrix}2 \\ 1\end{bmatrix} 
  + C_2\begin{bmatrix}1 \\ -1\end{bmatrix}
  = \begin{bmatrix}1 \\ 0\end{bmatrix}
$$

最后得到$C_1=\frac{1}{3},C_2=\frac{1}{3}$，完成解如下：

$$
  u(t)=\frac{1}{3}e^{0 \cdot t} \begin{bmatrix}2 \\ 1\end{bmatrix}
  + \frac{1}{3}e^{-3t} \begin{bmatrix}1 \\ -1\end{bmatrix}
$$

随着时间推移，$u(0)$的最后达到稳态，$u_0$一部分转移到$u_1$，在无限大时，可得到如下

$$
  u(\infty) = \frac{1}{3} \begin{bmatrix}2 \\ 1\end{bmatrix}
$$

上面最后收敛有点类似马尔科夫矩阵，列和为0，总有一个特征值为0，最后也具有稳定状态。最后稳定后，各个元素的之和与初始矩阵个元素之和相等。

根据上面例子，讨论解的稳定性，尤其是$2 \times 2$矩阵稳定性。

如果最大特征值是0,其他特征值实数部分小于0，那么具有稳定状态，虚数部分只负责转圈，不会对模长度产生影响。但是，如果矩阵反号，那么所有**特征值反号**，没有稳定态，最后会发散。

对于$2 \times 2$矩阵，如果需要达到稳定状态，特征值需要满足下面的要求，

* $Re(\lambda_1)+Re(\lambda_2) \le 0$ 
* $Re(\lambda_1) Re(\lambda_2) \ge 0$

一旦满足上面的条件，可以保证符合稳定的条件,$A=[0]_{2\times 2}$等号成立。

## 总结

$n \times n$矩阵的通解形式

$$
  u(t)=\sum_{i=1}^n{C_i e^{\lambda_i t} x_i}
$$

其中$x_i$是特征向量，$\lambda$是特征值，$C_i$是常数，通过初始向量$u(0)$与特征向量$x_1,\cdots,x_n$确定。

### 简化表示

下面定义一种更加优雅的形式，表示上述微分方程解，首先定义幂矩阵，启发来自$e^x$的泰勒展开

$$
  e^x = 1 + x + \frac{1}{2}x^2+\frac{1}{6}x^3+\cdots+\frac{1}{n!}x^n+\cdots
$$

那么，将形如$e^{At}$按照上面形式展开，结果仍然是矩阵！

$$
  e^{At} = I + At + \frac{1}{2}(At)^2+\frac{1}{6}(At)^3+\cdots+\frac{1}{n!}(At)^n+\cdots
$$

对$t$求导，得到如下值

$$
  \frac{d(e^{At})}{dt} = A + At+A\frac{1}{2}(At)^2+\cdots+A\frac{1}{(n-1)!}(At)^{n-1}+\cdots = Ae^{At}
$$

所以$u(t) = e^{At}u(0)$是微分方程的解。

假设特向量足够，那么可以将上面的公式进一步简化，**得到与之前微分方程解的联系**，

$$
\begin{align}
  e^{At}&=I + S \Lambda s^{-1}t + \frac{1}{2}(S \Lambda s^{-1}t)(S \Lambda s^{-1}t) + \cdots \\
        &=S(I + \Lambda t+ \frac{1}{2} \Lambda^2t + \cdots)S^{-1} \\
        &=Se^{\Lambda t}S^{-1} \qquad (2)
\end{align}
$$

将(2)代入解中，

$$
  u(t) = Se^{\Lambda t}S^{-1}u(0) = Se^{\Lambda t}S^{-1}Sc=Se^{\Lambda t}c 
  =\begin{bmatrix} x_1 & \cdots & x_n \end{bmatrix} 
  \begin{bmatrix} 
    e^{\lambda_1 t} &   &   \\
    & \ddots & \\
    & & e^{\lambda_n t} \\
  \end{bmatrix} 
  \begin{bmatrix} C_1 \\ \vdots \\ C_n \end{bmatrix} 
  =\sum_{i=1}^n{C_i e^{\lambda_i t} x_i}
$$

## 练习

在网络扩展建模中会用到，

求解下面微分方程
$$
  \frac{du}{dt}=\beta Au
$$

通解仍是

$$
  u = C e^{\beta \lambda t}x
$$

代入微分方程

$$
  Left = \frac{d(C e^{\beta \lambda t}x)}{dt} = C \beta e^{\beta \lambda t} \lambda x
$$

$$
  Right =\beta A C e^{\beta \lambda t}x = C \beta e^{\beta \lambda t} Ax =C \beta  e^{\beta \lambda t} \lambda x
$$


$C$计算与之前一致，完毕！

### 问题2：高阶线性微分方程

求解

$$
  ay^{(3)}+by^{(2)}+cy^{(1)}+dy + e = 0
$$

变化

$$
  y^{(3)}= -\frac{b}{a}y^{(2)} - \frac{c}{a}y^{(1)} -\frac{d}{a}y - \frac{e}{a}, a \ne 0
$$

设

$$
  u=\begin{bmatrix}y^{(2)} \\ y^{(1)} \\  y \\ 1 \end{bmatrix}
$$


构建线性矩阵微分方程


$$
  \frac{du}{dt} 
  = \begin{bmatrix}y^{(3)} \\ y^{(2)} \\  y^{(1)} \\ 0 \end{bmatrix}
  =
  \begin{bmatrix}  
   -\frac{b}{a} & - \frac{c}{a} & -\frac{d}{a} & - \frac{e}{a} \\  
  1 & 0 & 0 & 0 \\  
  0 & 1 & 0 & 0 \\ 
  0 & 0 & 0 & 0 \end{bmatrix}
  \begin{bmatrix}y^{(2)} \\ y^{(1)} \\  y \\ 1 \end{bmatrix}
$$


## 傅里叶级数

傅里叶级数利用了正交基的思想，首先我们先回顾一下向量的基，假设在$R^n$空间中，有n个正交向量$v_1,v_2,\cdots,v_n$，那么任意向量$x$可表示为：

$$
  x = c_1v_1 + c_2v_2 + \cdots + c_nv_n
$$

由于是正交基，计算系数$c_i$可以非常简单，上面等式两边同时乘以$v_i$，

$$
  v_i^Tx = c_iv_i^Tv_i \Rightarrow c_i = \frac{v_i^Tx }{v_i^Tv_i}
$$

如果正交基是是单位向量，那么可以简化为$c_i = v_i^Tx$。


在介绍傅里叶级数之前，先介绍连续函数的内积。向量内积可以认为是离散函数上，对应元素乘积之和。连续函数的内积，概念类似，只是将求和换成积分，其他一致，是不是很优雅的衍生了一个新的定义，如函数$f(x),g(x)$,其点积如下:

$$
  (f(x), g(x)) = \int_{0}^{2\pi} f(x)g(x) dx
$$


后面的积分都在$[0, 2\pi]$之间讨论，因为三角函数式周期函数，傅里叶级数是使用三角函数对任意函数展开。同理，函数的模长平方定义如下：


$$
  (f(x), f(x)) = \int_{0}^{2\pi} \left(f(x)\right)^2 dx
$$


**例1** 正交函数

$$
  \int_{0}^{2\pi} \sin x \cos x dx
  = \int_{0}^{2\pi} \frac{1}{2} \sin 2x dx
  = \left[-\frac{1}{4}\cos 2x \right]_{0}^{2\pi}
  = 0
$$

上面例子说明$\sin x$与$\cos x$正交！


**例2** 通用正交三角函数

$$
  \int_{0}^{2\pi} \sin ax \cos bx dx \\
  \int_{0}^{2\pi} \sin ax \sin bx dx \\
  \int_{0}^{2\pi} \cos ax \cos bx dx
$$

首先，回顾几个相关的三角公式，根据[二角和差公式](http://baike.baidu.com/view/959840.htm)导出

$$
  \sin \alpha \cos \beta = \frac{\sin (\alpha + \beta) + \sin (\alpha - \beta)}{2} \\
  \sin \alpha \sin \beta = \frac{\cos (\alpha - \beta) - \cos(\alpha + \beta)}{2} \\
  \cos \alpha \cos \beta = \frac{\cos (\alpha - \beta) + \cos(\alpha + \beta)}{2}
$$

将三角公式代入上面的积分公式，可以将积变成和，方便积分，如下

$$
  \int_{0}^{2\pi} \frac{\sin (a+b)x + \sin (a-b)x}{2} dx 
  = -\frac{1}{2} \left[\frac{1}{a + b} \cos (a+b)x
   + \frac{1}{a - b} \cos (a-b)x \right]_{0}^{2\pi} \\
  \int_{0}^{2\pi} \frac{\cos(a-b)x - \cos(a+b)x}{2} dx 
  = \frac{1}{2} \left[\frac{1}{a - b} \sin (a-b)x
   - \frac{1}{a+b} \sin (a+b)x \right]_{0}^{2\pi} \\
  \int_{0}^{2\pi} \frac{\cos(a-b)x + \cos(a+b)x}{2} dx 
  = \frac{1}{2} \left[\frac{1}{a - b} \sin (a-b)x
   + \frac{1}{a+b} \sin (a+b)x \right]_{0}^{2\pi}
$$

当$a,b \in N$时，上面三个等式均为0，也就是此时，

$$
\sin ax与\sin bx正交 \\
\cos ax与\cos bx正交 \\
\sin ax与\cos bx正交
$$

所以，根据基于向量的类似方法，在$[0,2\pi]$之间的可积（不一定连续）函数$f(x)$，可以展开为如下形式

$$
f(x) = a_0 + a_1 \cos x + b_1\sin x + a_2 \cos 2x + b_2 \sin 2x + \cdots
$$

 
接下来，可以按照向量的类似方法，计算系数，可以[参考三角函数积分](https://zh.wikipedia.org/wiki/%E4%B8%89%E8%A7%92%E5%87%BD%E6%95%B0%E7%A7%AF%E5%88%86%E8%A1%A8)。首先，两边乘以$\cos nx$，并且在$[0,2\pi]$定积分，根据正交，有如下

$$
  \int_{0}^{2\pi} f(x)\cos(nx) dx= \int_{0}^{2\pi} a_n \cos^2(nx)dx=a_n\pi  
  \Rightarrow
  a_n = \frac{1}{\pi}\int_{0}^{2\pi} f(x)\cos(nx) dx
$$

然后两边乘以$\sin nx$，

$$
  \int_{0}^{2\pi} f(x)\sin(nx)dx= \int_{0}^{2\pi} a_n \sin^2(nx) dx=b_n\pi 
  \Rightarrow
  b_n = \frac{1}{\pi}\int_{0}^{2\pi} f(x)\sin(nx) dx
$$

当$x=0$时，计算系数$a_0$,

$$
  \int_{0}^{2\pi} a_0 dx= \int_{0}^{2\pi}f(x)dx \Rightarrow a_0=\frac{1}{2\pi} \int_{0}^{2\pi}f(x)dx
$$


**练习** 方波的傅里叶级数展开

设$[0,2\pi]$之间的方波函数如下，

$$
  f(x) =
\begin{cases}
1,  & x \in [0,\pi) \\
-1, & x \in (\pi,2\pi]
\end{cases}
$$
 
根据上面公式，分别计算$a_0,a_n和b_n$,

$$
  a_0 = \frac{1}{2\pi}
  \left(\int_{0}^{\pi}1dx + \int_{\pi}^{2\pi}(-1)dx  \right) 
  = 0 \\
  a_n = \frac{1}{\pi}\left(\int_{0}^{\pi}\cos(nx)dx + \int_{\pi}^{2\pi}(-1)\cos(nx)dx  \right)
  =\frac{1}{\pi n}\left[\sin(nx)\right]_{0}^{\pi}-\frac{1}{\pi n} \left[\sin(nx)\right]_{\pi}^{2\pi} = 0 \\
  b_n = \frac{1}{\pi}\left(\int_{0}^{\pi}\sin(nx)dx + \int_{\pi}^{2\pi}(-1)\sin(nx)dx  \right) 
  =\frac{1}{\pi n}\left[-\cos(nx)\right]_{0}^{\pi}-\frac{1}{\pi n} \left[-\cos(nx)\right]_{\pi}^{2\pi} = \frac{2}{\pi n}(1-\cos(n\pi))
$$

对于$b_n$，需要根据奇偶来计算具体值,

$$
  b_n = \begin{cases}
  \frac{4}{n\pi}, & n是奇数\\
  0, & n是偶数
  \end{cases}
$$


所以，最后展开结果为：

$$
f(x) = \frac{4}{\pi}(\frac{\sin(x)}{1} + \frac{\sin(3x)}{3} + \frac{\sin(5x)}{5} + \cdots)
$$



 

